### ISSUE TITLE
实现方法

### ISSUE THREAD

**Issue by liuJianHui88** [fouber/blog#11]
能不能举例子，然后做个教程啊，虽然这个很详细了，但看起来还是晕。

**Comment by fouber** [comment]
@liuJianHui88 

稍安勿躁，我还在酝酿其他文章，都会一一说明的

**Comment by marsoln** [comment]
@fouber 云龙兄 你这个前端工程化系列文章写的很棒 有没有考虑出书啊？

**Comment by fouber** [comment]
@marsoln 
正在写作，这些章节是书中的部分内容

**Comment by Galen-Yip** [comment]
@fouber  👍🏻

**Comment by atian25** [comment]
拖稿很久了 -.-!!

**Comment by marsoln** [comment]
@fouber 云龙兄，书出了麻烦告知一下。
