### ISSUE TITLE
关于前端开发的一些疑问，请教下

### ISSUE THREAD

**Issue by lenxeon** [fouber/blog#15]
先做个自我介绍吧
我是做web端的，主要是后端java，前端方面：目前掌握的技术上css/less/js(主要是jquery和extjs)由于用extjs比较多，所以对前端组件化，模块化也有一定的了解。最近学了段时间的react webpack也看了你的博客，加上目前我遇上的问题，突然对前端产生了强烈的兴趣。

我目前遇上的问题：我公司的项目是做 [鱼骨软件](http://www.fishim.cn/ ) 企业软件的，项目规模不算大，大概分了十几个模块（或者叫子系统更合适），比如：任务，考勤，CRM，报销这样。而且每个子系统大概有十几个到二三十个页面不等，目前我的项目的开发结构大致如下

/project/src/common 一些通用组件，button tab panel 等等
/project/src/hr hr想关
project/src/crm crm相关

每个目录下面又有
/index.html
/images
/css
/js
/tpl (arttemplate 模板)
在这些目录下再细分模块

目前整个项目是前后端完全分离的，所有的请求都是通过ajax异步加载。

* 就上面的想法和下面的一些打算我希望能从你这得到一些意见和建议
* 我的打算是每个子项目都做成单页面应用，当然目前还不打算引入backbone, react这样的技术。仅仅是纯粹的通过js加载数据，结合arttemplate渲染到页面上，我的顾虑是引入这两个技术中的任一一个或者同时会造成项目进度的delay,毕竟我自己还是半调子，前端的负责人和开发者经验也不多。
* 究竟是amd还是cmd还是整体打包为一个JS的问题我是这样看的，在模块化的开发中，肯定是需要引入外部js的，这时必然要选一种模块化的方式，我打算结合fis3做开发，但我暂时还没有搞清楚我究竟应该选哪种，希望你指点下。另外发布的时候是每个模块打成一个js好还是让它异步加载好呢？我自己还是想打成两个js一个是comm.js 一个是子系统如hr.js
*目前那些arttemplate 模板我是通过ajax加载进来的，但我发现如果用fis3我想改变tpl目录下的文件的发布路径，js里打包结果ajax路径是没有换的，我不知道fis3下这些模块应该如何处理。或许我知道其中一种方式，就是在index.html里全部使用<link rel="import" href="xxx.html?__inline">的方式引进去，好像有点笨笨的。
* 看的越多就发现前端要走的路还很长，工程化，模块化(mvc)，组件化，打包上线部署工作，fis3目前虽然有不少例子，但感觉demo都是些小案例，还是有一点感觉跟实际的项目差异比较大，希望能看到一个比较大型点的实战示例。

**Comment by nimojs** [comment]
我来打个酱油，实战示例请参考 http://scrat.io/#!/index

**Comment by lenxeon** [comment]
@nimojs 恩，一站式服务，感觉比fis3的信息更详细，更集中，更适合中型一些的项目参考

**Comment by lenxeon** [comment]
@nimojs 我还是觉得各个子系统下放一个配置文件的方式或许更好？

**Comment by lenxeon** [comment]
@lenxeon 测试

**Comment by lenxeon** [comment]
@admin 测试
