### ISSUE TITLE
前端工程适合任何项目吗，是不是应该从小项目就开始试着使用前端工程化

### ISSUE THREAD

**Issue by lanting2009** [fouber/blog#22]
最近公司做的项目就做了前端工程化，用了gulp,less这些，但是我个人不知道学前端工程化如何入手，怎么用小项目自己练手，网上这方面的资料貌似也比较少，从基础开始的，请问大神，是否有基础的前端工程化比较详细的资料呢

**Comment by PetersonLian** [comment]
教你一招问人的方式。找到对方的github主页，然后按照email，发邮过去。
你这样开个issue做法欠妥。可以把issue关闭了。

**Comment by atian25** [comment]
目前就云龙博客上那几篇, 可以仔细看看.
他的书跳票很久了, 很忙没办法...

问题比较泛, 先 close 了.
