### ISSUE TITLE
能列举个前端工程师技能套装吗

### ISSUE THREAD

**Issue by codepandy** [fouber/blog#24]
你好，我一直做的工作比较杂，一般都是公司指哪打哪，所以没有那个区域的技术比较精，现在想专做前端，但现在前端知识图谱瞬间太广太杂了，如果想专做前端开发，首选需要学什么样的框架或工具，希望帮忙指点个方向，现在公司使用的是requirejs，另外结合一些其他的组件开发，自学了一段angularjs和nodejs，但现在公司不用，只是了解。

**Comment by ivanberry** [comment]
我也是自学，天下再变，唯原生不动，以不变应万变

**Comment by MiYogurt** [comment]
https://github.com/phodal/developer

http://skill.phodal.com/

http://html5ify.com/fks/

我叫骚年雷轰~不谢。

**Comment by MiYogurt** [comment]
最后削上一份前端rank，跟着趋势走向世盖。 https://www.awesomes.cn/rank/

**Comment by codepandy** [comment]
@MiYogurt 
非常感谢，这回答太有价值 了

**Comment by airyland** [comment]
@MiYogurt 为什么Rethinkdb会被归入前端趋势呢？ https://www.awesomes.cn/rank/?sort=trend

**Comment by MiYogurt** [comment]
@airyland 其实我根本就不清楚这货是什么，但是我稍微看了下介绍， 为什么不是呢？ 实时应用那么好用，而且此项目一直在维护，最后一次更新是5天前。 假如你问的是为什么跟前端扯上了关系，很明显文档里面出现了JavaScript，也就是node.js，再想想meteor。好像一切都说的过去了。

**Comment by airyland** [comment]
@MiYogurt Rethinkdb我们有在使用，其实我认为Rethinkdb纯粹是数据库，它只有各个语言的SDK.，和Meteor还是不一样的。Rethinkdb同个团队出的[Horizon](https://horizon.io/) 和Meteor更相似。

**Comment by MiYogurt** [comment]
@airyland 这就要问写这个算法的人了，我觉得应该是这个数据库就跟mongodb差不多吧，跟node比较配。O(∩_∩)O哈哈，瞎说说，没用过这种东西，东西太多学不过来了，还在进阶大师的途中。

**Comment by JimmyLv** [comment]
@MiYogurt 这个好，已注册，想请教一下前端排名是怎么算的？

**Comment by MiYogurt** [comment]
-。- 自己去找他们的github地址呗，又不是我写的，我程度还没到这个水准。 @JimmyLv
