### ISSUE TITLE
有没有刚学前端的小伙伴？

### ISSUE THREAD

**Issue by supervsky** [fouber/blog#26]
接触web前端好久了，但是一直没做出什么东西。用Github也只是会用几个简单操作，根本就没弄清楚Git对项目有多少帮助。有没有刚学前端的伙伴，有没有一些简单小项目，可以一起完成啊？

一个人也可以做，不过做着做着就有些烦了，需要学习的东西太多，而且没有人讨论遇到问题也不得到及时解决。

若有人想做一些小东西，想招人一起做，我能没有洪荒之力，但也能贡献得微薄之力啊！

**Comment by liu-dongyu** [comment]
你在人家的blog里面随便开issues这样真的好吗？ ..

**Comment by supervsky** [comment]
@liu-dongyu 我也欢迎你和博主来我blog开issue.

**Comment by shahuyang** [comment]
sb，以后被给我发这种邮件





在 2016-08-17 18:01:09，"Tyson" <notifications@github.com> 写道：


@liu-dongyu 我也欢迎你和博主来我blog开issue.

**Comment by wszgxa** [comment]
@shahuyang 好好学学英文。。。还有好好学学素质。。。

**Comment by JasinYip** [comment]
这是一个两千多人关注的博客，当你在发之前，你应该考虑清楚你这种行为是否会对博主以及其他人造成打扰，以及这种打扰是否有意义。

你欢迎别人去你博客里提这种无意义的问题，不代表你在他的博客里提这种无意义的问题就是一种礼貌的行为。

**Comment by BuaaJoseph** [comment]
害的我退订了

**Comment by PetersonLian** [comment]
有没有可能题主真的是太小白，才开issue的？
毕竟，他说github都不太会用。
所以也不要一味骂他，温柔点。

**Comment by Thyiad** [comment]
谁能关闭掉这个issue，后来人不要再回了，邮件会一直跳。。

**Comment by JasinYip** [comment]
> 谁能关闭掉这个issue，后来人不要再回了，邮件会一直跳。。

你可以点右边的 Unsubscribe

**Comment by BuaaJoseph** [comment]
@JasinYip 我点了，还是能收到。。。

**Comment by evenluo** [comment]
@BuaaJoseph 你watch了这个项目吧？

**Comment by JasinYip** [comment]
> @BuaaJoseph 你watch了这个项目吧？

讲道理即使 watch 了，点了某 issue 的 unsubscribe 应该也不会收到才对……

**Comment by macnie** [comment]
watch了一年了。现在取消了关注了，我真是受够了。国人的项目真能哔哔。谁都比谁能。以后再也不会弹了。

**Comment by wy-ang** [comment]
@supervsky 自己先反思下这样做对不对，然后把这个issues删了，我先取关了。

**Comment by shahuyang** [comment]
你有病啊，别给我发邮件了


发自 网易邮箱大师
在2016年09月01日 23:22，张云龙 写道:

Closed #26.

**Comment by samcello** [comment]
诶，我说你是智障吗，

发这种无聊邮件，

拜托，我不认识你，没必要发邮件给你。

对你已屏蔽，

碍于品德，我就不直接问候你祖宗十八代了。


2016-09-05 7:42 GMT+08:00 陈云飞 <notifications@github.com>:

**Comment by samcello** [comment]
对收到我上封邮件的小朋友们说声对不起，没搞清楚情况下发了过激的回话。

**Comment by Hinsteny** [comment]
会用Websocket结合activeMQ实现消息实时推送吗。。。
