### ISSUE TITLE
div.io的邀请码在登录页上面有邀请码申请渠道，此楼勿盖，看到了麻烦删下

### ISSUE THREAD

**Issue by yhda110** [fouber/blog#29]
感谢@Eastegg分享申请流程：
打开div.io的登录页上面有邀请码申请渠道。
希望站长把邀请码申请按钮放到注册页面，我前几次都是打开注册页看不到邀请码申请渠道，后来偶尔进到登录页才看到的。

**Comment by zheeeng** [comment]
也借地方求一个，air.island.e@gmail.com
谢谢龙哥

**Comment by NikitaCP** [comment]
同求一个邀请码，谢谢啦！

2016-10-17 14:41 GMT+08:00 Zheeeng <notifications@github.com>:

**Comment by webx32** [comment]
FUMH-W1CB-PHTO-2OEM

**Comment by webx32** [comment]
FUMH-W1CB-PHTO-2OEM

**Comment by webx32** [comment]
6YMP-LD4Y-BRML-ZEYI

**Comment by webx32** [comment]
1VLI-YQEM-SHWX-0BZ9

**Comment by yan513683375** [comment]
同求一枚邀请码，513683375@qq.com


原始邮件
发件人:Andynotifications@github.com
收件人:fouber/blogblog@noreply.github.com
发送时间:2016年10月18日(周二) 08:39
主题:Re: [fouber/blog] 龙哥，可以给我个div.io的邀请码吗？ (#29)


1VLI-YQEM-SHWX-0BZ9

**Comment by NewBieOfSoftClass** [comment]
龙哥，求一枚邀请码，谢谢. wj083@126.com

**Comment by alienwow** [comment]
同求一枚邀请码  谢谢龙哥。   wuwenhao0327@gmail.com

**Comment by Leoahboom** [comment]
同求一枚邀请码，感谢龙哥！ cuijiaxu211@gmail.com

**Comment by magicalcosmos** [comment]
同求一枚邀请码，感谢龙哥！brodyliao@msn.com

**Comment by Eastegg** [comment]
先给大家道个歉，不好意思打扰了，希望管理关闭本Issues

@yhda110  开了一个不好的先例，请大家尽量不要在Issues里做这种与主题无关的事情，而是用来讨论问题。watch的人都会收到你们的comment会烦死的。
另外打开div.io的登录页上面有邀请码申请渠道。
另外希望站长把邀请码申请按钮放到注册页面，我前几次都是打开注册页看不到邀请码申请渠道，后来偶尔进到登录页才看到的。
在同时可以看到登录和注册按钮时，没账号的人是不会点登陆的吧。。。

**Comment by zhaozhe0831** [comment]
![image](https://cloud.githubusercontent.com/assets/12945873/19463774/6fee332c-9529-11e6-8e82-6fd9503cf5e6.png)

**Comment by xjiaoi** [comment]
龙哥 同求div.io<http://div.io> 码

ecaixiaoji@hotmail.com<mailto:ecaixiaoji@hotmail.com>


在 2016年10月18日，08:38，Andy <notifications@github.com<mailto:notifications@github.com>> 写道：


6YMP-LD4Y-BRML-ZEYI

**Comment by macnie** [comment]
求个邀请码你们都不会私信吗？非要每天弹邮件？作为开发者，有没有使用GIT的一点基本常识？ 
 
------------------ 原始邮件 ------------------
发件人: "xjiaoi"; 
发送时间: 2016年10月18日(星期二) 下午4:29
收件人: "fouber/blog"; 
主题: Re: [fouber/blog] div.io的邀请码在登录页上面有邀请码申请渠道，此楼勿盖，看到了麻烦删下 (#29)

 
龙哥 同求div.io<http://div.io> 码 
 
 ecaixiaoji@hotmail.com<mailto:ecaixiaoji@hotmail.com> 
 
 
 在 2016年10月18日，08:38，Andy <notifications@github.com<mailto:notifications@github.com>> 写道： 
 
 
 6YMP-LD4Y-BRML-ZEYI

**Comment by chenzhutian** [comment]
实在太恶心了....开个issue来讨码，恶心所有人，还丢自己脸，何苦？

**Comment by web240** [comment]
是的,这个没必要在这里公开讨论，毕竟可以私信

**Comment by zhaojunlike** [comment]
都是chinese，hah
