### ISSUE TITLE
借宝地发个招聘信息，再找不到人，老板要打死我，被逼无奈。

### ISSUE THREAD

**Issue by jaywcjlove** [fouber/blog#30]
求靠谱人才，欢迎简历砸死我。我实在是厚颜无耻，但是没有办法，先拿简历砸死我吧。

工作位置：__`上海青浦`__

## 招聘

- 前端开发工程师
- 程序员鼓励师(行政人员要带这个功能)
- 视觉设计师(Sketch/PS)
- 移动端ReactNative方向
- 后端开发工程师Nodejs 方向
- PC客户端Electron开发方向

精通JS就好了。高级／初级都需要

要跳槽的发邮件给我哦 **wowohoo@qq.com** 跪求简历😭

你们杀了我吧，我是被逼的。
为了不打扰大家，发邮件跟我聊聊吧，工作位置在上海青浦。

你可点击这里 https://github.com/settings/blocked_users 将我屏蔽掉，就不会收到骚扰信息。

你可以下面方法退订这条 issue 的[通知](#issuecomment-254420419) 

不是我舍不得花钱，是我没有太多预算。

**Comment by hotoo** [comment]
老板不打死你你过来我保证不打死你。

**Comment by airyland** [comment]
提醒大家，这种知道会打扰大家还在issue发招聘帖，并且招聘帖内容没有什么水平，甚至没什么节操(个人意见)的公司不去也罢。

帮大家了解下这家公司**上海亮金信息技术有限公司**：
- https://www.v2ex.com/t/312287
- https://cnodejs.org/topic/57ff3c38487e1e4578afb49c

**Comment by jaywcjlove** [comment]
对不起，打扰你们了

@airyland 上面都是我发的，招聘信息是真实的。
小公司招聘难，@hotoo 我怕你犯法，凡是转发了的人，可以赔偿精神损失费，我发红包给你们，谢谢。

**Comment by Hinsteny** [comment]
你可以去拉勾网上注册个账号，比较详细贴心的写一下招聘信息，相信你可以找到合适你们公司的人的！
这个Issue关了吧

**Comment by Lt-grint** [comment]
知道无耻还发issues，你这样一发，两千多人都收到你的推送了

**Comment by hhstore** [comment]
提醒大家, 每个 issue 右下角, 有个 `Notifications` 处, 可以 ` ignoring this thread.` 忽略掉该 issue.

顺便, 找到 发这种 issue 的人主页, 屏蔽掉这种素质低的人.

![image](https://cloud.githubusercontent.com/assets/3252130/19466901/bd927b08-9540-11e6-9b6f-b1b55daacd81.png)

**Comment by atian25** [comment]
https://github.com/settings/blocked_users

**Comment by HankLiang** [comment]
老板不打死你你过来我保证不打死你。

**Comment by jaywcjlove** [comment]
@Hinsteny 51job 和 智联招聘都发了，来面试的人连js 都不会，一个切页面的还说自己是前端开发工程师。

这里面应该发过来的简历都是比较垂直的，至少有点料的，至少能写js的，我放两天关闭了，打扰了不好意思，你可以点 旁边的 `Unsubscribe` 按钮退订这个 `issue` 的通知，谢谢！@Lt-grint

**Comment by likunNet** [comment]
舍得花钱还怕招不到人，别再这里讨人嫌了，越这样越找不到。

**Comment by macnie** [comment]
那就让你老板直接打死你好了

**Comment by HankLiang** [comment]
把你们公司的基本信息发我邮箱把， 我瞅下先。 前端的渣渣

**Comment by fuchao2012** [comment]
这个通知关掉也没啥用了，反正已经收到了。为 hr 点个赞吧，都不容易

**Comment by atian25** [comment]
鉴于最近垃圾消息太多, 瓶子又太忙了, 我这边会帮忙清理下垃圾.
