### ISSUE TITLE
静态HTML页面用什么工具进行构建？

### ISSUE THREAD

**Issue by hilite2000** [fouber/blog#31]
请教个问题，要生成一个静态页面的网站。
相同的内容不详都在每个页面上复制一份，有什么办法像是js编译一样。
能把公共部分抽取出来，放到不同的html里，在不同的主内容页面里引用他们。
然后能编译成一个个独立的页面。
该用什么样的工具，Grunt？gulp？，望不吝赐教。

**Comment by atian25** [comment]
随便找个模板引擎，构建期编译下即可。

或者看下 hexo

**Comment by zhaojunlike** [comment]
@hilite2000 我最近在做一个项目，全静态的，你可以参考一下，我使用得gulp，通过构建sass和gulp-include来进行开发的，git进行项目管理，不知道对你又没用，我也是新手，还望指教

**Comment by nonoroazoro** [comment]
webpack html plugin
