### ISSUE TITLE
作为新手最近卡到了JavaScript

### ISSUE THREAD

**Issue by x851285009** [fouber/blog#32]
看着各位大大谈笑风声，
我得努力了，
（目前连在GITHUB建静态站都不会的小白）

**Comment by codering** [comment]
就凭你在别人的blog上随意开issue, 足以证明你非常非常非常小白了！！！

**Comment by zhaojunlike** [comment]
哈哈哈，我点一个倒赞

**Comment by x1ah** [comment]
新开 issue 之前也最好看看别人的 issue 是什么内容的。要不然容易尴尬。

**Comment by x851285009** [comment]
抱歉

**Comment by hackjutsu** [comment]
Issue 不是贴吧……

**Comment by Zikzin** [comment]
连issue是什么都不知道的小白 让你们开心下
