### ISSUE TITLE
中小公司是否有必要搭建私有cnpm仓库

### ISSUE THREAD

**Issue by csnikey** [fouber/blog#38]
看见阿里，美团等公司都搭建了私有的npm仓库，想问下从工程化的角度，中小公司是否有必要搭建自己的cnpm仓库。希望能从以下几个角度回答：
1 像bat等大厂的npm模块主要是存储那些模块的，有哪些管理模块的方式
2 cnpm搭建之后，什么样的模块适合发布在这里面，像有些样式或者图片资源适合发布为npm模块么；在使用的时候，公司的模块要和外部npm模块放到一个目录管理么，要不要加区分
3 使用模块以及使用cdn这些网络地址是否有冲突，因为目前的开发中如果使用cdn网络地址就不会打包到产出文件中；如果使用模块，那么因为存在依赖，就会被打包，导致打包文件过大。像使用elementui的时候，就是开发时导入了依赖，导致打包出来js很大。

**Comment by atian25** [comment]
cnpm 的维护成本还是不低的，也可以考虑 npm 的 private 服务，https://www.npmjs.com/pricing

> 1 像bat等大厂的npm模块主要是存储那些模块的，有哪些管理模块的方式

私有的，不希望对外公开的模块。管理模块不知道你具体想问啥，一般是发布遵循 semver 规则。

> 2 cnpm搭建之后，什么样的模块适合发布在这里面，像有些样式或者图片资源适合发布为npm模块么；在使用的时候，公司的模块要和外部npm模块放到一个目录管理么，要不要加区分

- 同上，私有的会发布到这。由于 cnpm 会同步 npm 的源，所以对于使用者就只用连 cnpm。
- 可以组件化和复用的都可以当做模块。
- 都在 `node_modules` 下，使用者根本不用管。私有库一般都会上自己的 scope，如 `@ali/xxx`

> 3 使用模块以及使用cdn这些网络地址是否有冲突，因为目前的开发中如果使用cdn网络地址就不会打包到产出文件中；如果使用模块，那么因为存在依赖，就会被打包，导致打包文件过大。像使用elementui的时候，就是开发时导入了依赖，导致打包出来js很大。

- 配置 `npmignore` 设置希望发布的文件
- 通过 npm scripts 的 `prepublish` 配置发布前构建脚本
