### ISSUE TITLE
私人博客，请勿私自发起 Issue

### ISSUE THREAD

**Issue by Prayashearnki** [fouber/blog#49]
**请注意：这是一个私人博客，请不要在这里练习新建 Issue，你的每一条回复，都会有几千的 watcher 收到邮件，请慎用。**

**如果恶意发布 Issue，将会加入 GitHub 黑名单。**

**Comment by M-Nemo** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我最近正在忙碌中，无法亲自回复您的邮件。我将在忙碌束后，尽快给您回复。

**Comment by JeffCP9527** [comment]
邮件已收到~

**Comment by ccfung** [comment]
谢谢。您的邮件已收到，我会尽快处理。Thank you. Your email is received and will be handled  as soon as possible.

**Comment by staxing** [comment]
您好，邮件已经收到，我将尽快给您回复。谢谢~~

**Comment by FairyYang** [comment]
我收到了

**Comment by tachibanakaori** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by qzoushi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by helingjuan** [comment]
收到。谢谢

**Comment by cy920820** [comment]
？？？

这么多自动回复

**Comment by zhizhilong** [comment]
What happened ！！！

**Comment by FatDoge** [comment]
真服了 有自动回复的设置一下啊，邮箱一直不停

**Comment by heiye9** [comment]
发的好，已经被自动回复轰炸了
