### ISSUE TITLE
The project is great. Is there a flutter version? Flutter is an open source mobile application software development kit developed by Google for developing applications for Android, iOS, Web, Windows, macOS, Linux Desktop, Google Fuchsia. Flutter is making efforts to games, Metaverse, and web3. ![flutter](https://user-images.githubusercontent.com/122947293/213731917-caf3dfd0-db1d-4b1c-ba21-85d8f0985396.png) https://github.com/flutter/flutter 项目非常棒 有flutter版本吗？Flutter是一个由谷歌开发的开源移动应用软件开发工具包，用于为Android、iOS、Web、We'bWindows、macOS、Linux Desktop、Google Fuchsia开发应用。 Flutter正在向游戏、元宇宙、web3发力。

### ISSUE THREAD

**Issue by swordbe** [fouber/blog#50]
The project is great. Is there a flutter version? Flutter is an open source mobile application software development kit developed by Google for developing applications for Android, iOS, Web, Windows, macOS, Linux Desktop, Google Fuchsia. Flutter is making efforts to games, Metaverse, and web3. ![flutter](https://user-images.githubusercontent.com/122947293/213731917-caf3dfd0-db1d-4b1c-ba21-85d8f0985396.png) https://github.com/flutter/flutter 项目非常棒 有flutter版本吗？Flutter是一个由谷歌开发的开源移动应用软件开发工具包，用于为Android、iOS、Web、We'bWindows、macOS、Linux Desktop、Google Fuchsia开发应用。 Flutter正在向游戏、元宇宙、web3发力。

**Comment by 7greenfrog7** [comment]
您的来信我已收到~我会在看到的第一时间回复给您~

**Comment by M-Nemo** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我最近正在忙碌中，无法亲自回复您的邮件。我将在忙碌束后，尽快给您回复。

**Comment by zhouqimark** [comment]
你好，如果你收到这封邮件。可能 只是因为我想测试一下假期自动回复功能。。

**Comment by JeffCP9527** [comment]
邮件已收到~

**Comment by ccfung** [comment]
谢谢。您的邮件已收到，我会尽快处理。Thank you. Your email is received and will be handled  as soon as possible.

**Comment by staxing** [comment]
您好，邮件已经收到，我将尽快给您回复。谢谢~~

**Comment by FairyYang** [comment]
我收到了

**Comment by tachibanakaori** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by liyueS777** [comment]
这是来自QQ邮箱的假期自动回复邮件

**Comment by qzoushi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by rookie233333** [comment]
好的，邮件我已收到！我会尽快阅读并回复的！

**Comment by heihuahe** [comment]
收到。谢谢
